name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Build with dotnet
      run: dotnet build --configuration Release netcore-api/netcore-api/netcore-api.csproj
 
    - name: Hello World
      run: echo Hello world, run number = $NBR
      env:
        NBR: ${{github.RUN_NUMBER}}
#    - name: dotnet publish
#      run: dotnet publish -c Release -o netcore-api ./netcore-api/netcore-api
#    - name: Restore dependencies
#      run: dotnet restore
#    - name: Build
#      run: dotnet build --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
